adding implementation for validating login
Transurgeon/shopping-cart pull request #25
Opened 2023-11-23 17:05 UTC by Transurgeon

adds implementation for ConcordiaID verification and email verification.

relevant issues: #4 and some progress towards #12.

2023-11-23 22:46 UTC, cedparadis commented
of course your implementation does not work because you need to use your methods in RegisterSrv which process the data from the form. 
* Add implementation of your method into the RegisterSrv

2023-11-23 22:48 UTC, cedparadis requested changes, later dismissed
of course your implementation does not work because you need to use your methods in RegisterSrv which process the data from the form.

* Add implementation of your method into the RegisterSrv

2023-11-24 04:18 UTC, Transurgeon commented
> of course your implementation does not work because you need to use your methods in RegisterSrv which process the data from the form.
> 
> * Add implementation of your method into the RegisterSrv

I made some changes to ``registerStudentUser`` which is called by RegisterSrv.
My issue is that even If I pass a valid ConcordiaID, it will flag as being wrong.

2023-11-24 04:28 UTC, Transurgeon commented
now I am getting an error with the Jakarta email.. what should do about that?
Can you check if this issue is also on your end @cedparadis.
<img width="730" alt="image" src="https://github.com/Transurgeon/shopping-cart/assets/89562186/079ccb01-2990-4400-8ec9-c120944f6b10">

2023-11-24 04:37 UTC, Transurgeon commented
Ok I just verified and we are able to create new users with the forms. Also the error message do display properly.
<img width="542" alt="image" src="https://github.com/Transurgeon/shopping-cart/assets/89562186/6ae8ac63-135c-4b99-a8f7-46b128e2d125">
I think we can merge this for now. I will look into the Jakarta email at a later time.

2023-11-24 21:40 UTC, chloedaull reviewed
excellent work overall, just have a question about what the isRegtd if statement returns

2023-11-24 21:40 UTC, chloedaull commented on src/com/shashi/service/impl/UserServiceImpl.java
> +			return "Email Id Already Registered!";
pourquoi le return status et le return string qui dit la meme chose?

2023-11-24 21:52 UTC, chloedaull approved these changes

2023-11-24 22:07 UTC, merged